# Generated by Django 3.2.4 on 2021-11-14 08:29

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kyc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('agentId', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Please enter valid phone number. Correct format is 04XXXXXXXX', regex='^\\+?1?\\d{9,15}$')])),
                ('residential_Address', models.TextField()),
                ('communication_address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Kyc_secondary_police',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_document', models.CharField(choices=[('Department of Veterans Affairs (DVA) card', 'Department of Veterans Affairs (DVA) card'), ('Centrelink card (with reference number)', 'Centrelink card (with reference number)'), ('Birth Certificate Extract', 'Birth Certificate Extract'), ('Birth card (NSW Births, Deaths, Marriages issue only)', 'Birth card (NSW Births, Deaths, Marriages issue only)'), ('Medicare card', 'Medicare card'), ('Credit card or account card', 'Credit card or account card'), ('Australian Marriage certificate (Australian Registry issue only)', 'Australian Marriage certificate (Australian Registry issue only)'), ('Decree Nisi / Decree Absolute (Australian Registry issue only)', 'Decree Nisi / Decree Absolute (Australian Registry issue only)'), ('Change of name certificate (Australian Registry issue only)', 'Change of name certificate (Australian Registry issue only)'), ('Bank statement (showing transactions)', 'Bank statement (showing transactions)'), ('Property lease agreement - current address', 'Property lease agreement - current address'), ('Taxation assessment notice', 'Taxation assessment notice'), ('Australian Mortgage Documents - Current address', 'Australian Mortgage Documents - Current address'), ('Rating Authority - Current address eg Land Rates', 'Rating Authority - Current address eg Land Rates'), ('Utility Bill - electricity, gas, telephone - Current address (less than 12 months old)', 'Utility Bill - electricity, gas, telephone - Current address (less than 12 months old)'), ('Reference from Indigenous Organisation', 'Reference from Indigenous Organisation'), ('Documents issued outside Australia (equivalent to Australian documents).Must have official translation attached', 'Documents issued outside Australia (equivalent to Australian documents).Must have official translation attached')], max_length=150)),
                ('points', models.IntegerField()),
                ('document', models.FileField(upload_to='AgentKycDocument/')),
                ('kyc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agent.kyc')),
            ],
        ),
        migrations.CreateModel(
            name='Kyc_primary_police',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_document', models.CharField(choices=[('Foreign Passport (current)', 'Foreign Passport (current)'), ('Australian Passport (current or expired within last 2 years but not cancelled)', 'Australian Passport (current or expired within last 2 years but not cancelled)'), ('Australian Citizenship Certificate', 'Australian Citizenship Certificate'), ('Full Birth certificate (not birth certificate extract)', 'Full Birth certificate (not birth certificate extract)'), ('Certificate of Identity issued by the Australian Government to refugees and non Australian citizens for entry to Australia', 'Certificate of Identity issued by the Australian Government to refugees and non Australian citizens for entry to Australia'), ('Australian Driver Licence/Learner’s Permit', 'Australian Driver Licence/Learner’s Permit'), ('Current (Australian) Tertiary Student Identification Card', 'Current (Australian) Tertiary Student Identification Card'), ('Photo identification card issued for Australian regulatory purposes (e.g. Aviation/Maritime Security identification, security industry etc.)', 'Photo identification card issued for Australian regulatory purposes (e.g. Aviation/Maritime Security identification, security industry etc.)'), ('Government employee ID (Australian Federal/State/Territory)', 'Government employee ID (Australian Federal/State/Territory)'), ('Defence Force Identity Card (with photo or signature)', 'Defence Force Identity Card (with photo or signature)')], max_length=150)),
                ('points', models.IntegerField()),
                ('document', models.FileField(upload_to='AgentKycDocument/')),
                ('kyc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agent.kyc')),
            ],
        ),
        migrations.CreateModel(
            name='Kyc_member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('afca_membership', models.CharField(max_length=50)),
                ('aggreator_contractor', models.CharField(max_length=50)),
                ('Aggregato_ManagerName', models.CharField(blank=True, max_length=50, null=True)),
                ('Aggregato_ManagerNumber', models.CharField(blank=True, max_length=50, null=True)),
                ('ABN_Number', models.CharField(blank=True, max_length=50, null=True)),
                ('Diploma_certificate', models.FileField(upload_to='AgentKycDocument/diploma/')),
                ('kyc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agent.kyc')),
            ],
        ),
    ]
