# Generated by Django 3.2.4 on 2021-11-14 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kyc_primary_police',
            name='name_of_document',
            field=models.CharField(choices=[('Foreign Passport (current)', 'Foreign Passport (current)'), ('Australian Passport (current or expired within last 2 years but not cancelled)', 'Australian Passport (current or expired within last 2 years but not cancelled)'), ('Australian Citizenship Certificate', 'Australian Citizenship Certificate'), ('Full Birth certificate (not birth certificate extract)', 'Full Birth certificate (not birth certificate extract)'), ('Certificate of Identity issued by the Australian Government to refugees and non Australian citizens for entry to Australia', 'Certificate of Identity issued by the Australian Government to refugees and non Australian citizens for entry to Australia'), ('Australian Driver Licence/Learner’s Permit', 'Australian Driver Licence/Learner’s Permit'), ('Current (Australian) Tertiary Student Identification Card', 'Current (Australian) Tertiary Student Identification Card'), ('Photo identification card issued for Australian regulatory purposes (e.g. Aviation/Maritime Security identification, security industry etc.)', 'Photo identification card issued for Australian regulatory purposes (e.g. Aviation/Maritime Security identification, security industry etc.)'), ('Government employee ID (Australian Federal/State/Territory)', 'Government employee ID (Australian Federal/State/Territory)'), ('Defence Force Identity Card (with photo or signature)', 'Defence Force Identity Card (with photo or signature)')], max_length=12500),
        ),
    ]
