# Generated by Django 3.1.4 on 2021-01-08 10:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_bizpartner', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=15)),
                ('commissions', models.CharField(max_length=20)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('referred_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phnumber', models.IntegerField(blank=True)),
                ('email_confirmed', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_status', models.CharField(max_length=15)),
                ('loan_wname', models.CharField(max_length=15)),
                ('loan_wphone', models.IntegerField()),
                ('loan_wemail', models.CharField(max_length=40)),
                ('loan_type', models.CharField(choices=[('Buy a Home', 'Buy a Home'), ('Refinance', 'Refinance')], max_length=15)),
                ('vehicle', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=25)),
                ('vehicle_worth', models.IntegerField(blank=True)),
                ('vehicle_money', models.IntegerField(blank=True)),
                ('carloan_pay', models.CharField(blank=True, choices=[('yes', 'yes'), ('no', 'no')], max_length=25)),
                ('accounts', models.IntegerField()),
                ('superannuation', models.IntegerField()),
                ('additional_asset', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=25)),
                ('home_content', models.IntegerField()),
                ('credit_card', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=25)),
                ('credit_limit', models.IntegerField()),
                ('liability_loan', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=25)),
                ('loans', models.IntegerField()),
                ('employment_type', models.CharField(choices=[('Employee', 'Employee'), ('Self-employed', 'Self-employed'), ('Not working', 'Not working')], max_length=50)),
                ('annual_salary', models.IntegerField()),
                ('monthly_expense', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50)),
                ('signature', models.CharField(max_length=50)),
                ('pdfurl', models.CharField(max_length=50, null=True)),
                ('status', models.CharField(max_length=50, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BankInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bankname', models.CharField(max_length=50)),
                ('acname', models.CharField(max_length=50)),
                ('acno', models.IntegerField(max_length=50)),
                ('bankisc', models.CharField(max_length=50)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Additional_liabilities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types', models.CharField(choices=[('tax debt', 'tax debt'), ('other lines of credit', 'other lines of credit')], max_length=35)),
                ('owned', models.IntegerField()),
                ('description', models.CharField(max_length=500)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='user.loan')),
            ],
        ),
        migrations.CreateModel(
            name='Additional_assets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types', models.CharField(choices=[('Term Deposit', 'Term Deposit'), ('Shares', 'Shares'), ('Managed Funds', 'Managed Funds'), ('Gifts', 'Gifts')], max_length=35)),
                ('description', models.CharField(max_length=25)),
                ('total_value', models.IntegerField()),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='user.loan')),
            ],
        ),
    ]
