# Generated by Django 3.1.4 on 2021-01-09 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210109_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additional_liabilities',
            name='owned',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='loan',
            name='accounts',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='loan',
            name='annual_salary',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='loan',
            name='credit_limit',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='loan',
            name='home_content',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_wphone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loans',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='loan',
            name='monthly_expense',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='loan',
            name='superannuation',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='loan',
            name='vehicle_money',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='loan',
            name='vehicle_worth',
            field=models.CharField(max_length=20),
        ),
    ]
