# Generated by Django 3.1.4 on 2021-01-11 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20210109_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='credit_limit',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
