# Generated by Django 3.1.4 on 2021-01-13 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20210111_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='additional_assets',
            name='select',
            field=models.CharField(default=1, max_length=35),
            preserve_default=False,
        ),
    ]
