# Generated by Django 3.1.4 on 2021-01-24 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20210114_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additional_assets',
            name='description',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='additional_assets',
            name='total_value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='additional_liabilities',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='additional_liabilities',
            name='owned',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='accounts',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='additional_asset',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=25),
        ),
        migrations.AlterField(
            model_name='loan',
            name='annual_salary',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='carloan_pay',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=25),
        ),
        migrations.AlterField(
            model_name='loan',
            name='credit_card',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=25),
        ),
        migrations.AlterField(
            model_name='loan',
            name='home_content',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='liability_loan',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=25),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_status',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_wemail',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_wname',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_wphone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loans',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='monthly_expense',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='superannuation',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='vehicle',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=25),
        ),
        migrations.AlterField(
            model_name='loan',
            name='vehicle_money',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='vehicle_worth',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
