# Generated by Django 3.1.4 on 2021-01-25 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20210124_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
    ]
