# Generated by Django 3.1.4 on 2021-01-28 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_loan_created_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=20)),
                ('number', models.CharField(max_length=20)),
                ('subject', models.CharField(max_length=20)),
                ('message', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='additional_liabilities',
            name='types',
            field=models.CharField(blank=True, choices=[('tax debt', 'tax debt'), ('other lines of credit', 'other lines of credit')], max_length=35, null=True),
        ),
    ]
