# Generated by Django 3.1.5 on 2021-02-05 09:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20210201_1341'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='business',
            options={'verbose_name_plural': 'Business'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name_plural': 'Inbox'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Profile Verification'},
        ),
        migrations.AlterModelOptions(
            name='referral',
            options={'verbose_name_plural': 'Bizpartner Commissions'},
        ),
        migrations.AlterModelOptions(
            name='verification',
            options={'verbose_name_plural': 'BizPartner'},
        ),
        migrations.AddField(
            model_name='contact',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='referral',
            name='commission_status',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(max_length=2500),
        ),
    ]
