# Generated by Django 3.1.5 on 2021-02-06 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20210205_2023'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='business',
            options={'verbose_name_plural': 'Bizpartner Data'},
        ),
    ]
