# Generated by Django 3.1.5 on 2021-02-07 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_auto_20210207_0557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='pdfurl',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
