# Generated by Django 3.1.5 on 2021-02-09 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_business_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='agreement/'),
        ),
    ]
