# Generated by Django 3.1.5 on 2021-02-09 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_auto_20210209_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='BizpartnerAgreement/'),
        ),
    ]
