# Generated by Django 3.1.5 on 2021-02-09 14:55

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_auto_20210210_0110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='pdfurl',
        ),
        migrations.AlterField(
            model_name='business',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to=user.models.user_directory_path),
        ),
    ]
