# Generated by Django 3.1.5 on 2021-02-09 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_auto_20210210_0155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
