# Generated by Django 3.1.5 on 2021-02-09 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_auto_20210210_0552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='BizpartnerAgreement/'),
        ),
    ]
