# Generated by Django 3.1.5 on 2021-02-10 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_auto_20210210_0621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='status',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
