# Generated by Django 3.1.5 on 2021-02-12 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_auto_20210211_0223'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='email_id',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='business',
            name='phone_no',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
