# Generated by Django 3.1.5 on 2021-02-12 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_auto_20210213_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='email_id',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
