# Generated by Django 3.1.5 on 2021-02-12 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_auto_20210213_0043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='email_id',
        ),
        migrations.AddField(
            model_name='business',
            name='email',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
