# Generated by Django 3.1.5 on 2021-02-15 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0030_auto_20210215_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='fullname',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='business',
            name='signature',
            field=models.CharField(max_length=50),
        ),
    ]
