# Generated by Django 3.1.5 on 2021-02-15 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0032_auto_20210216_0509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='carloan_pay',
            field=models.BooleanField(blank=True, choices=[('Yes', 'true'), ('No', 'false')], max_length=25, null=True),
        ),
    ]
