# Generated by Django 3.1.5 on 2021-02-15 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0035_auto_20210216_0616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='carloan_pay',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=25),
        ),
    ]
