# Generated by Django 3.1.5 on 2021-02-15 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0036_auto_20210216_0620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='carloan_pay',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=25, null=True),
        ),
    ]
