# Generated by Django 3.1.5 on 2021-02-17 06:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0038_auto_20210217_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='accounts',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator('^[0-9]*$', message='Only numbers are allowed.')]),
        ),
        migrations.AlterField(
            model_name='loan',
            name='annual_salary',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator('^[0-9]*$', message='Only numbers are allowed.')]),
        ),
        migrations.AlterField(
            model_name='loan',
            name='credit_limit',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator('^[0-9]*$', message='Only numbers are allowed.')]),
        ),
        migrations.AlterField(
            model_name='loan',
            name='home_content',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator('^[0-9]*$', message='Only numbers are allowed.')]),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loans',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator('^[0-9]*$', message='Only numbers are allowed.')]),
        ),
        migrations.AlterField(
            model_name='loan',
            name='monthly_expense',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator('^[0-9]*$', message='Only numbers are allowed.')]),
        ),
        migrations.AlterField(
            model_name='loan',
            name='superannuation',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator('^[0-9]*$', message='Only numbers are allowed.')]),
        ),
        migrations.AlterField(
            model_name='loan',
            name='vehicle_money',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator('^[0-9]*$', message='Only numbers are allowed.')]),
        ),
        migrations.AlterField(
            model_name='loan',
            name='vehicle_worth',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator('^[0-9]*$', message='Only numbers are allowed.')]),
        ),
    ]
