# Generated by Django 3.1.5 on 2021-02-17 06:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0039_auto_20210217_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankinfo',
            name='acno',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[0-9]*$', message='Only numbers are allowed.')]),
        ),
        migrations.AlterField(
            model_name='bankinfo',
            name='bankisc',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[0-9]*$', message='Only numbers are allowed.')]),
        ),
    ]
