# Generated by Django 3.2.4 on 2021-10-13 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='kyc_done',
            field=models.BooleanField(default=False),
        ),
    ]
