# Generated by Django 3.2.4 on 2022-01-12 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_profile_kyc_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='underprocess_loans',
            name='admin_approve',
            field=models.BooleanField(default=False),
        ),
    ]
