# Generated by Django 3.2.4 on 2021-12-18 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kyc_member',
            old_name='Aggregato_ManagerName',
            new_name='Aggregator_ManagerName',
        ),
        migrations.RenameField(
            model_name='kyc_member',
            old_name='Aggregato_ManagerNumber',
            new_name='Aggregator_ManagerNumber',
        ),
        migrations.RenameField(
            model_name='kyc_member',
            old_name='aggreator_contractor',
            new_name='Aggregator_contractor',
        ),
    ]
