# Generated by Django 3.2.4 on 2022-01-15 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0002_auto_20211218_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kyc',
            name='agentId',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
